name: hejtter
description: A mobile app for Hejto.
publish_to: 'none'
version: 0.0.9+9

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  cached_network_image: ^3.2.3
  timeago: ^3.3.0

  dart_emoji: ^0.2.0+2
  infinite_scroll_pagination: ^3.2.0
  extended_image: ^6.3.4
  any_link_preview: ^2.0.9
  flutter_markdown: ^0.6.13
  url_launcher: ^6.1.7
  photo_view: ^0.14.0
  dropdown_button2: ^1.9.2
  flutter_displaymode: ^0.4.1
  flutter_downloader: ^1.9.1
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  package_info_plus: ^3.0.2
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.7
  loading_animation_widget: ^1.2.0+4
  cookie_jar: ^3.0.1
  equatable: ^2.0.5
  hydrated_bloc: ^9.0.0
  flutter_secure_storage: ^7.0.1
  flutter_email_sender: ^5.2.0
  share_plus: ^6.3.0
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  another_flushbar: ^1.12.29
  uni_links: ^0.5.1
  app_settings: ^4.2.0
  flutter_html: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/